services:
  - type: web
    name: factura-validator
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y wget gnupg unzip
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
    startCommand: gunicorn app:app
    envVars:
      - key: ENVIRONMENT
        value: PROD
      - key: GROQ_API_KEY
        sync: false
      - key: SUNAT_RUC
        sync: false
      - key: SUNAT_USER
        sync: false
      - key: SUNAT_PASS
        sync: false
